version: '3.8'

services:
  zabbix-srv:
    image: zabbix/zabbix-appliance:latest
    container_name: Zabbix-Server
    ports:
      - 80:80
      - 10051:10051
    volumes:
      - /home/rafael/cursos/devops/Zabbix:/var/lib/mysql
    
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server