Vagrant.configure("2") do |config|

  config.vm.define "vb1" do |vb1|
    vb1.vm.box = "ubuntu/focal64"
    vb1.vm.network "public_network" , ip: "192.168.0.110" , bridge: "wlp1s0"
    vb1.vm.provision "shell", path: "script-zabbix-agent.sh"
    vb1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      vb.name = "vm-focal64"
    end
  end
  
  config.vm.define "vb2" do |vb2|
    vb2.vm.box = "ubuntu/jammy64"
    vb2.vm.network "public_network" , ip: "192.168.0.154" , bridge: "wlp1s0"
    vb2.vm.provision "shell", path: "script.sh"
    vb2.vm.synced_folder "./docker-compose", "/home/vagrant/compose" 
    vb2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
      vb.name = "Zabbix-Srv"
    end
  end
end